//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.NameDateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NameDateService.NameDateSoap")]
    public interface NameDateSoap {
        
        // CODEGEN: Generating message contract since element name nameInput from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintDateForName", ReplyAction="*")]
        Client.NameDateService.PrintDateForNameResponse PrintDateForName(Client.NameDateService.PrintDateForNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintDateForName", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.NameDateService.PrintDateForNameResponse> PrintDateForNameAsync(Client.NameDateService.PrintDateForNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintDateForNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintDateForName", Namespace="http://tempuri.org/", Order=0)]
        public Client.NameDateService.PrintDateForNameRequestBody Body;
        
        public PrintDateForNameRequest() {
        }
        
        public PrintDateForNameRequest(Client.NameDateService.PrintDateForNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintDateForNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameInput;
        
        public PrintDateForNameRequestBody() {
        }
        
        public PrintDateForNameRequestBody(string nameInput) {
            this.nameInput = nameInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintDateForNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintDateForNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.NameDateService.PrintDateForNameResponseBody Body;
        
        public PrintDateForNameResponse() {
        }
        
        public PrintDateForNameResponse(Client.NameDateService.PrintDateForNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintDateForNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintDateForNameResult;
        
        public PrintDateForNameResponseBody() {
        }
        
        public PrintDateForNameResponseBody(string PrintDateForNameResult) {
            this.PrintDateForNameResult = PrintDateForNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NameDateSoapChannel : Client.NameDateService.NameDateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NameDateSoapClient : System.ServiceModel.ClientBase<Client.NameDateService.NameDateSoap>, Client.NameDateService.NameDateSoap {
        
        public NameDateSoapClient() {
        }
        
        public NameDateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NameDateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameDateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameDateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.NameDateService.PrintDateForNameResponse Client.NameDateService.NameDateSoap.PrintDateForName(Client.NameDateService.PrintDateForNameRequest request) {
            return base.Channel.PrintDateForName(request);
        }
        
        public string PrintDateForName(string nameInput) {
            Client.NameDateService.PrintDateForNameRequest inValue = new Client.NameDateService.PrintDateForNameRequest();
            inValue.Body = new Client.NameDateService.PrintDateForNameRequestBody();
            inValue.Body.nameInput = nameInput;
            Client.NameDateService.PrintDateForNameResponse retVal = ((Client.NameDateService.NameDateSoap)(this)).PrintDateForName(inValue);
            return retVal.Body.PrintDateForNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.NameDateService.PrintDateForNameResponse> Client.NameDateService.NameDateSoap.PrintDateForNameAsync(Client.NameDateService.PrintDateForNameRequest request) {
            return base.Channel.PrintDateForNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.NameDateService.PrintDateForNameResponse> PrintDateForNameAsync(string nameInput) {
            Client.NameDateService.PrintDateForNameRequest inValue = new Client.NameDateService.PrintDateForNameRequest();
            inValue.Body = new Client.NameDateService.PrintDateForNameRequestBody();
            inValue.Body.nameInput = nameInput;
            return ((Client.NameDateService.NameDateSoap)(this)).PrintDateForNameAsync(inValue);
        }
    }
}
