//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name firstNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThreeNumbers", ReplyAction="*")]
        Client.ServiceReference1.AddThreeNumbersResponse AddThreeNumbers(Client.ServiceReference1.AddThreeNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThreeNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddThreeNumbersResponse> AddThreeNumbersAsync(Client.ServiceReference1.AddThreeNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddThreeNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddThreeNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddThreeNumbersRequestBody Body;
        
        public AddThreeNumbersRequest() {
        }
        
        public AddThreeNumbersRequest(Client.ServiceReference1.AddThreeNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddThreeNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string secondNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string thirdNumber;
        
        public AddThreeNumbersRequestBody() {
        }
        
        public AddThreeNumbersRequestBody(string firstNumber, string secondNumber, string thirdNumber) {
            this.firstNumber = firstNumber;
            this.secondNumber = secondNumber;
            this.thirdNumber = thirdNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddThreeNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddThreeNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddThreeNumbersResponseBody Body;
        
        public AddThreeNumbersResponse() {
        }
        
        public AddThreeNumbersResponse(Client.ServiceReference1.AddThreeNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddThreeNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddThreeNumbersResult;
        
        public AddThreeNumbersResponseBody() {
        }
        
        public AddThreeNumbersResponseBody(int AddThreeNumbersResult) {
            this.AddThreeNumbersResult = AddThreeNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddThreeNumbersResponse Client.ServiceReference1.WebService1Soap.AddThreeNumbers(Client.ServiceReference1.AddThreeNumbersRequest request) {
            return base.Channel.AddThreeNumbers(request);
        }
        
        public int AddThreeNumbers(string firstNumber, string secondNumber, string thirdNumber) {
            Client.ServiceReference1.AddThreeNumbersRequest inValue = new Client.ServiceReference1.AddThreeNumbersRequest();
            inValue.Body = new Client.ServiceReference1.AddThreeNumbersRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.thirdNumber = thirdNumber;
            Client.ServiceReference1.AddThreeNumbersResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).AddThreeNumbers(inValue);
            return retVal.Body.AddThreeNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddThreeNumbersResponse> Client.ServiceReference1.WebService1Soap.AddThreeNumbersAsync(Client.ServiceReference1.AddThreeNumbersRequest request) {
            return base.Channel.AddThreeNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddThreeNumbersResponse> AddThreeNumbersAsync(string firstNumber, string secondNumber, string thirdNumber) {
            Client.ServiceReference1.AddThreeNumbersRequest inValue = new Client.ServiceReference1.AddThreeNumbersRequest();
            inValue.Body = new Client.ServiceReference1.AddThreeNumbersRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.secondNumber = secondNumber;
            inValue.Body.thirdNumber = thirdNumber;
            return ((Client.ServiceReference1.WebService1Soap)(this)).AddThreeNumbersAsync(inValue);
        }
    }
}
