//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.AddTwoServiceSoap")]
    public interface AddTwoServiceSoap {
        
        // CODEGEN: Generating message contract since element name firstNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwo", ReplyAction="*")]
        Client.ServiceReference2.AddTwoResponse AddTwo(Client.ServiceReference2.AddTwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference2.AddTwoResponse> AddTwoAsync(Client.ServiceReference2.AddTwoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwo", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference2.AddTwoRequestBody Body;
        
        public AddTwoRequest() {
        }
        
        public AddTwoRequest(Client.ServiceReference2.AddTwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string secondNumber;
        
        public AddTwoRequestBody() {
        }
        
        public AddTwoRequestBody(string firstNumber, string secondNumber) {
            this.firstNumber = firstNumber;
            this.secondNumber = secondNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference2.AddTwoResponseBody Body;
        
        public AddTwoResponse() {
        }
        
        public AddTwoResponse(Client.ServiceReference2.AddTwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTwoResult;
        
        public AddTwoResponseBody() {
        }
        
        public AddTwoResponseBody(int AddTwoResult) {
            this.AddTwoResult = AddTwoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddTwoServiceSoapChannel : Client.ServiceReference2.AddTwoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddTwoServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference2.AddTwoServiceSoap>, Client.ServiceReference2.AddTwoServiceSoap {
        
        public AddTwoServiceSoapClient() {
        }
        
        public AddTwoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddTwoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference2.AddTwoResponse Client.ServiceReference2.AddTwoServiceSoap.AddTwo(Client.ServiceReference2.AddTwoRequest request) {
            return base.Channel.AddTwo(request);
        }
        
        public int AddTwo(string firstNumber, string secondNumber) {
            Client.ServiceReference2.AddTwoRequest inValue = new Client.ServiceReference2.AddTwoRequest();
            inValue.Body = new Client.ServiceReference2.AddTwoRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.secondNumber = secondNumber;
            Client.ServiceReference2.AddTwoResponse retVal = ((Client.ServiceReference2.AddTwoServiceSoap)(this)).AddTwo(inValue);
            return retVal.Body.AddTwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference2.AddTwoResponse> Client.ServiceReference2.AddTwoServiceSoap.AddTwoAsync(Client.ServiceReference2.AddTwoRequest request) {
            return base.Channel.AddTwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference2.AddTwoResponse> AddTwoAsync(string firstNumber, string secondNumber) {
            Client.ServiceReference2.AddTwoRequest inValue = new Client.ServiceReference2.AddTwoRequest();
            inValue.Body = new Client.ServiceReference2.AddTwoRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.secondNumber = secondNumber;
            return ((Client.ServiceReference2.AddTwoServiceSoap)(this)).AddTwoAsync(inValue);
        }
    }
}
