//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.addTwoNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="addTwoNumbers.addtwonumbersSoap")]
    public interface addtwonumbersSoap {
        
        // CODEGEN: Generating message contract since element name firstNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        Client.addTwoNumbers.AddTwoNumbersResponse AddTwoNumbers(Client.addTwoNumbers.AddTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.addTwoNumbers.AddTwoNumbersResponse> AddTwoNumbersAsync(Client.addTwoNumbers.AddTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Client.addTwoNumbers.AddTwoNumbersRequestBody Body;
        
        public AddTwoNumbersRequest() {
        }
        
        public AddTwoNumbersRequest(Client.addTwoNumbers.AddTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string secondNumber;
        
        public AddTwoNumbersRequestBody() {
        }
        
        public AddTwoNumbersRequestBody(string firstNumber, string secondNumber) {
            this.firstNumber = firstNumber;
            this.secondNumber = secondNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.addTwoNumbers.AddTwoNumbersResponseBody Body;
        
        public AddTwoNumbersResponse() {
        }
        
        public AddTwoNumbersResponse(Client.addTwoNumbers.AddTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTwoNumbersResult;
        
        public AddTwoNumbersResponseBody() {
        }
        
        public AddTwoNumbersResponseBody(int AddTwoNumbersResult) {
            this.AddTwoNumbersResult = AddTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface addtwonumbersSoapChannel : Client.addTwoNumbers.addtwonumbersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addtwonumbersSoapClient : System.ServiceModel.ClientBase<Client.addTwoNumbers.addtwonumbersSoap>, Client.addTwoNumbers.addtwonumbersSoap {
        
        public addtwonumbersSoapClient() {
        }
        
        public addtwonumbersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public addtwonumbersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addtwonumbersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public addtwonumbersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.addTwoNumbers.AddTwoNumbersResponse Client.addTwoNumbers.addtwonumbersSoap.AddTwoNumbers(Client.addTwoNumbers.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbers(request);
        }
        
        public int AddTwoNumbers(string firstNumber, string secondNumber) {
            Client.addTwoNumbers.AddTwoNumbersRequest inValue = new Client.addTwoNumbers.AddTwoNumbersRequest();
            inValue.Body = new Client.addTwoNumbers.AddTwoNumbersRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.secondNumber = secondNumber;
            Client.addTwoNumbers.AddTwoNumbersResponse retVal = ((Client.addTwoNumbers.addtwonumbersSoap)(this)).AddTwoNumbers(inValue);
            return retVal.Body.AddTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.addTwoNumbers.AddTwoNumbersResponse> Client.addTwoNumbers.addtwonumbersSoap.AddTwoNumbersAsync(Client.addTwoNumbers.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.addTwoNumbers.AddTwoNumbersResponse> AddTwoNumbersAsync(string firstNumber, string secondNumber) {
            Client.addTwoNumbers.AddTwoNumbersRequest inValue = new Client.addTwoNumbers.AddTwoNumbersRequest();
            inValue.Body = new Client.addTwoNumbers.AddTwoNumbersRequestBody();
            inValue.Body.firstNumber = firstNumber;
            inValue.Body.secondNumber = secondNumber;
            return ((Client.addTwoNumbers.addtwonumbersSoap)(this)).AddTwoNumbersAsync(inValue);
        }
    }
}
