//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WeatherForecast {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherForecast.WeatherForecastServiceSoap")]
    public interface WeatherForecastServiceSoap {
        
        // CODEGEN: Generating message contract since element name PrintForecastResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintForecast", ReplyAction="*")]
        Client.WeatherForecast.PrintForecastResponse PrintForecast(Client.WeatherForecast.PrintForecastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.WeatherForecast.PrintForecastResponse> PrintForecastAsync(Client.WeatherForecast.PrintForecastRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintForecastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintForecast", Namespace="http://tempuri.org/", Order=0)]
        public Client.WeatherForecast.PrintForecastRequestBody Body;
        
        public PrintForecastRequest() {
        }
        
        public PrintForecastRequest(Client.WeatherForecast.PrintForecastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PrintForecastRequestBody {
        
        public PrintForecastRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintForecastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintForecastResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.WeatherForecast.PrintForecastResponseBody Body;
        
        public PrintForecastResponse() {
        }
        
        public PrintForecastResponse(Client.WeatherForecast.PrintForecastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintForecastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintForecastResult;
        
        public PrintForecastResponseBody() {
        }
        
        public PrintForecastResponseBody(string PrintForecastResult) {
            this.PrintForecastResult = PrintForecastResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherForecastServiceSoapChannel : Client.WeatherForecast.WeatherForecastServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherForecastServiceSoapClient : System.ServiceModel.ClientBase<Client.WeatherForecast.WeatherForecastServiceSoap>, Client.WeatherForecast.WeatherForecastServiceSoap {
        
        public WeatherForecastServiceSoapClient() {
        }
        
        public WeatherForecastServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherForecastServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherForecastServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherForecastServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.WeatherForecast.PrintForecastResponse Client.WeatherForecast.WeatherForecastServiceSoap.PrintForecast(Client.WeatherForecast.PrintForecastRequest request) {
            return base.Channel.PrintForecast(request);
        }
        
        public string PrintForecast() {
            Client.WeatherForecast.PrintForecastRequest inValue = new Client.WeatherForecast.PrintForecastRequest();
            inValue.Body = new Client.WeatherForecast.PrintForecastRequestBody();
            Client.WeatherForecast.PrintForecastResponse retVal = ((Client.WeatherForecast.WeatherForecastServiceSoap)(this)).PrintForecast(inValue);
            return retVal.Body.PrintForecastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.WeatherForecast.PrintForecastResponse> Client.WeatherForecast.WeatherForecastServiceSoap.PrintForecastAsync(Client.WeatherForecast.PrintForecastRequest request) {
            return base.Channel.PrintForecastAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.WeatherForecast.PrintForecastResponse> PrintForecastAsync() {
            Client.WeatherForecast.PrintForecastRequest inValue = new Client.WeatherForecast.PrintForecastRequest();
            inValue.Body = new Client.WeatherForecast.PrintForecastRequestBody();
            return ((Client.WeatherForecast.WeatherForecastServiceSoap)(this)).PrintForecastAsync(inValue);
        }
    }
}
